services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - DB_HOST=db
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=ar_condicionado
      # MYSQL_USER: app_user
      # - MYSQL_ROOT_PASSWORD=SENHA
      # MYSQL_PASSWORD: app_password
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
  
volumes:
  db_data: